### ISSUE TITLE
js中的注释也会被编译

### ISSUE THREAD

**Issue by jipika** [hujinbin/webpack-i18n-loader#16]
![image](https://user-images.githubusercontent.com/59040157/231135104-74ba66d8-84b7-4378-93a0-1003a95b9ec4.png)

**Comment by hujinbin** [comment]
这个是版本的原因，应该已经修复过了

**Comment by jipika** [comment]
我是用的是最新版

**Comment by hujinbin** [comment]
试试 1.3.7 版本或者 1.3.10（最新） 版本 ， 中间两个版本（1.3.8，1.3.9）会取到注释。
