### ISSUE TITLE
当对象的key值是中文时，解析错误

### ISSUE THREAD

**Issue by ShuangDa1018** [hujinbin/webpack-i18n-loader#2]

**Comment by hujinbin** [comment]
请提供详细代码？示例

**Comment by hujinbin** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/23625357/187408313-516da7e1-6516-41e1-b9b5-10c617f60692.png">
不规范用法，如果后续要继续用中文做对象的key，可使用忽略功能

例：
// <i18n-ignore
let a = { '测试':123 }
// i18n-ignore>
