### ISSUE TITLE
js多个引号包含会出错

### ISSUE THREAD

**Issue by ShuangDa1018** [hujinbin/webpack-i18n-loader#3]

**Comment by ShuangDa1018** [comment]
![image](https://user-images.githubusercontent.com/66151395/186058586-3ba724a5-9187-47b6-82e8-304ba32837a3.png)

**Comment by ShuangDa1018** [comment]
<a-tooltip title="可点击圆圈内的 '且' '或' 进行逻辑切换">

**Comment by ShuangDa1018** [comment]
`` <a-form-model-item v-if="schemaType === 'vertex'" label="图标" :rules="[{ required: true, message: `请选择图标` }]">

**Comment by hujinbin** [comment]
> 图

这个只使用规范语法 required: true, message: `请选择图标`   ->   required: true, message: '请选择图标'

**Comment by hujinbin** [comment]
> ![image](https://user-images.githubusercontent.com/66151395/186058586-3ba724a5-9187-47b6-82e8-304ba32837a3.png)

中文和js方法混入
需改代码。
 ```
const newNum = num ? `(${num})`:''
tabs.push({key:'detail',name:`详情${newNum}`})
```
