### ISSUE TITLE
请问在uniapp上可以使用吗?

### ISSUE THREAD

**Issue by jipika** [hujinbin/webpack-i18n-loader#8]
如果可以使用的话可以给个文档嘛... 😘

**Comment by jipika** [comment]
我已经配置成功在uniapp中使用可以提供一个demo嘛

**Comment by hujinbin** [comment]
没有uniapp使用的demo，底层如果还是用的webpack的话，是能支持的，最新的uniapp好像已经是用vite了，vite是不支持的

**Comment by jipika** [comment]
我上传了一个uniapp 的使用此插件的demo,可以正确的工作
